### ISSUE TITLE
Kde Dolphin quickacess area not working

### ISSUE THREAD

**Issue by scho0ck** [cryptomator/integrations-linux#96]
Running Fedora 41 with Kde Plasma and the flatpak version 1.14.0 of cryptomator when I enable the option to add an unlocked vault to the quick access area it does not work and the cli shows the following error. Did I miss any setting/permission?

`17:21:52.409 [DBus-Signal-Receiver-1] INFO  o.p.k.f.dbus.handlers.SignalHandler - Received signal KWallet.walletAsyncOpened: {TransactionID: 3, handle: 438699984}
17:21:52.410 [DBus-Signal-Receiver-1] INFO  o.p.k.f.dbus.handlers.SignalHandler - Received signal KWallet.walletAsyncOpened: {TransactionID: 3, handle: 438699984}
17:21:53.535 [App Background Thread 002] ERROR org.cryptomator.common.vaults.Vault - Adding vault to quick access area failed
org.cryptomator.integrations.quickaccess.QuickAccessServiceException: Adding entry to KDE places file failed.
        at org.cryptomator.integrations.linux@1.5.0/org.cryptomator.linux.quickaccess.DolphinPlaces.add(DolphinPlaces.java:92)
        at org.cryptomator.desktop@1.14.0/org.cryptomator.common.vaults.Vault.addToQuickAccessInternal(Vault.java:219)
        at java.base/java.util.Optional.ifPresentOrElse(Unknown Source)
        at org.cryptomator.desktop@1.14.0/org.cryptomator.common.vaults.Vault.addToQuickAccess(Vault.java:210)
        at org.cryptomator.desktop@1.14.0/org.cryptomator.common.vaults.Vault.unlock(Vault.java:166)
        at org.cryptomator.desktop@1.14.0/org.cryptomator.ui.keyloading.KeyLoadingStrategy.use(KeyLoadingStrategy.java:79)
        at org.cryptomator.desktop@1.14.0/org.cryptomator.ui.unlock.UnlockWorkflow.call(UnlockWorkflow.java:76)
        at org.cryptomator.desktop@1.14.0/org.cryptomator.ui.unlock.UnlockWorkflow.call(UnlockWorkflow.java:34)
        at javafx.graphics@22.0.2/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.AtomicMoveNotSupportedException: /tmp/user-places.xbel.cryptomator.tmp -> /home/user/.local/share/user-places.xbel: Invalid cross-device link
        at java.base/sun.nio.fs.UnixFileSystem.move(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.move(Unknown Source)
        at java.base/java.nio.file.Files.move(Unknown Source)
        at org.cryptomator.integrations.linux@1.5.0/org.cryptomator.linux.quickaccess.DolphinPlaces.add(DolphinPlaces.java:89)
        ... 14 common frames omitted
`

**Comment by JaniruTEC** [comment]
Hey @scho0ck,
thank you for reporting this issue.
From a technical standpoint adding/removing a vault to/from the quick access area involves editing `~/.local/share/user-places.xbel`. To make sure that we don't corrupt that file, we first make a copy, edit that copy and then replace the original with a special move operation.
That special move doesn't work if `/tmp` and `~` are located on different partitions, which seems to be the case here.
Can you confirm this for me?

Consequently, there are probably no problems with your settings/permissions and therefore this issue can only be fixed on our end without too much effort on your side. I'm sorry about that.

~ JanriuTEC

**Comment by scho0ck** [comment]
@JaniruTEC Thanks for your quick reply. You're right indeed Fedora uses btrfs and root where tmp resides and home are on different subvolumes I didn't think this could cause an issue.
